services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  back:
    container_name: back
    build: ./backend
    volumes:
      - ./backend:/app
      - ./assets:/app/assets:ro
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - z3950
      - photo-scraper
    env_file:
      - ./.env

  scheduler:
    container_name: scheduler
    build: ./backend
    volumes:
      - ./backend:/app
    restart: always
    entrypoint: ["python", "worker.py"]
    depends_on:
      - db
      - z3950
      - photo-scraper
    env_file:
      - ./.env

  z3950:
    container_name: z3950
    build: ./z3950
    restart: always
    ports:
      - "8001:8001"    
    volumes:
      - ./z3950:/app

  photo-scraper:
    container_name: photo-scraper
    build: ./photo-scraper
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./photo-scraper:/app

volumes:
  postgres_data:
