"""Establishments2

Revision ID: ed6bfe80aa21
Revises: 482d6998b355
Create Date: 2026-03-03 09:46:50.633466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed6bfe80aa21'
down_revision: Union[str, Sequence[str], None] = '482d6998b355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_establishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queue', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'establishment_id', 'language', name='unique_book_establishment')
    )
    op.create_index(op.f('ix_book_establishment_book_id'), 'book_establishment', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_establishment_establishment_id'), 'book_establishment', ['establishment_id'], unique=False)
    op.create_index(op.f('ix_book_establishment_language'), 'book_establishment', ['language'], unique=False)
    op.create_index(op.f('ix_book_establishment_status'), 'book_establishment', ['status'], unique=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'normal_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'normal_author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.alter_column('user_books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.alter_column('books', 'normal_author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'normal_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_book_establishment_status'), table_name='book_establishment')
    op.drop_index(op.f('ix_book_establishment_language'), table_name='book_establishment')
    op.drop_index(op.f('ix_book_establishment_establishment_id'), table_name='book_establishment')
    op.drop_index(op.f('ix_book_establishment_book_id'), table_name='book_establishment')
    op.drop_table('book_establishment')
    op.drop_table('establishments')
    # ### end Alembic commands ###
