"""Autor y titulo normalizados

Revision ID: 976373906748
Revises: af0355235bd2
Create Date: 2026-02-12 20:59:42.213693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '976373906748'
down_revision: Union[str, Sequence[str], None] = 'af0355235bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('normal_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('books', sa.Column('normal_author', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_books_normal_author'), 'books', ['normal_author'], unique=False)
    op.create_index(op.f('ix_books_normal_title'), 'books', ['normal_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_normal_title'), table_name='books')
    op.drop_index(op.f('ix_books_normal_author'), table_name='books')
    op.drop_column('books', 'created_at')
    op.drop_column('books', 'normal_author')
    op.drop_column('books', 'normal_title')
    # ### end Alembic commands ###
