"""

Revision ID: f44d2a911e43
Revises: ed6bfe80aa21
Create Date: 2026-03-05 10:24:17.691266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f44d2a911e43'
down_revision: Union[str, Sequence[str], None] = 'ed6bfe80aa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_establishment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('book_establishment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('unique_book'), 'books', type_='unique')
    op.create_unique_constraint('unique_book', 'books', ['normal_title', 'normal_author'])
    op.create_index(op.f('ix_search_cache_id_book'), 'search_cache', ['id_book'], unique=False)
    op.alter_column('user_books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_search_cache_id_book'), table_name='search_cache')
    op.drop_constraint('unique_book', 'books', type_='unique')
    op.create_unique_constraint(op.f('unique_book'), 'books', ['title', 'author'], postgresql_nulls_not_distinct=False)
    op.alter_column('book_establishment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('book_establishment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
