"""drift check

Revision ID: 93af173722b7
Revises: c9d0e1f20311
Create Date: 2026-08-11 13:28:00.661812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93af173722b7'
down_revision: Union[str, Sequence[str], None] = 'c9d0e1f20311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_catalogs_catalog_id'), 'user_catalogs', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_user_catalogs_user_id'), 'user_catalogs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_establishments_establishment_id'), 'user_favorite_establishments', ['establishment_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_establishments_user_id'), 'user_favorite_establishments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_establishments_user_id'), table_name='user_favorite_establishments')
    op.drop_index(op.f('ix_user_favorite_establishments_establishment_id'), table_name='user_favorite_establishments')
    op.drop_index(op.f('ix_user_catalogs_user_id'), table_name='user_catalogs')
    op.drop_index(op.f('ix_user_catalogs_catalog_id'), table_name='user_catalogs')
    # ### end Alembic commands ###
